In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math 
import random as rand
from scipy.sparse import coo_matrix, csr_matrix, csc_matrix, vstack, find
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import PCA, IncrementalPCA
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

df=pd.read_csv('~/UMDDataChallenge/BlueYp713_UMD_2022/matrix_completion/data/matrix_dataset.csv', low_memory=False)
df = df.dropna()
df = df.drop(columns=['Unnamed: 0'])
df.head()

location  month  actor  event_sub_type
0     1.097      1      1               1
1     1.125      1      2               1
2     1.073      1      3               1
3     1.101      1      4               1
4     1.097      1      5               1

In [17]:
df.columns

Index(['location', 'month', 'actor', 'event_sub_type'], dtype='object')

In [18]:
location = np.unique(np.array(df['location'].values))
month = np.unique(np.array(df['month'].values))
actor = np.unique(np.array(df['actor'].values))
subevent = np.unique(np.array(df['event_sub_type'].values))

In [19]:
print(location)
print(month)
print(actor)
print(subevent)

[ 1.003  1.007  1.015 ... 56.035 56.037 56.039]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[   1    2    3 ... 3962 3963 3964]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [20]:
df.loc[df['location'] == 6.037, ['event_sub_type']].value_counts()

event_sub_type
1                 992
2                  48
10                 45
3                  27
4                   9
7                   9
9                   8
6                   2
5                   1
12                  1
14                  1
dtype: int64

In [21]:
df.loc[df['event_sub_type'] == 2, ['location']].value_counts()

location
11.001      49
6.037       48
36.061      47
41.051      33
21.111      20
            ..
12.125       1
12.109       1
12.099       1
36.113       1
56.001       1
Length: 295, dtype: int64

In [22]:
df['event_sub_type'].value_counts()

1     33859
2      1041
3       949
10      945
6       439
7       173
4       143
9        82
8        62
5        38
14       15
13       10
11        9
12        4
15        1
16        1
Name: event_sub_type, dtype: int64

In [23]:
dfarray = df.to_numpy()
print(df.isnull().sum())
#dfarray[~np.isnan(dfarray).any(axis=1)]

location          0
month             0
actor             0
event_sub_type    0
dtype: int64


In [24]:
print(dfarray)

[[1.0970e+00 1.0000e+00 1.0000e+00 1.0000e+00]
 [1.1250e+00 1.0000e+00 2.0000e+00 1.0000e+00]
 [1.0730e+00 1.0000e+00 3.0000e+00 1.0000e+00]
 ...
 [5.6021e+01 1.0000e+00 7.7000e+02 1.0000e+00]
 [5.6029e+01 1.0000e+00 1.8000e+01 1.0000e+00]
 [5.6037e+01 1.0000e+00 2.5730e+03 1.0000e+00]]


In [25]:
inputval = []
target = []
for i in range(len(dfarray)):
    inputval.append(list(dfarray[i][0:3]))
    target.append(dfarray[i][3])

In [28]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets, neighbors
from mlxtend.plotting import plot_decision_regions
from sklearn.neighbors import KNeighborsClassifier
import random 

model = KNeighborsClassifier(n_neighbors=10)

# Train the model using the training sets
model.fit(inputval,target)

#Predict Output
predicted= model.predict([[6.037,7,1]]) 
print(predicted)
predicted= model.predict([[11.001,9,5]]) 
print(predicted)

for i in range(10):
    l = random.choice(location)
    m = random.choice(month)
    a = random.choice(actor)
    predicted= model.predict([[l,m,a]]) 
    print(predicted)

[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]
[1.]


In [ ]:
def knn_comparison(data, k):
 x = data[[‘X’,’Y’]].values
 y = data[‘class’].astype(int).values
 clf = neighbors.KNeighborsClassifier(n_neighbors=k)
 clf.fit(x, y)
# Plotting decision region
 plot_decision_regions(x, y, clf=clf, legend=2)
# Adding axes annotations
 plt.xlabel(‘X’)
 plt.ylabel(‘Y’)
 plt.title(‘Knn with K=’+ str(k))
 plt.show()